config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :datasets, only: %i[show edit update destroy]
  resources :sources, only: %i[show edit update destroy]

  post 'sources/add_refs/:id' => 'sources#add_refs', as: 'add_refs_to_source'
  get 'sources/process/:id' => 'sources#data_proc', as: 'process_source'
  get 'sources/word_data/:id/:type/:slice' => 'sources#get_data', as: 'source_data',
      constraints: ->(req) { req.format == :json }
  get 'sources/relate_data/:id/:type' => 'sources#get_relate_data',
      as: 'source_relate_data', constraints: ->(req) { req.format == :json }

  get 'datasets/process/:id' => 'datasets#data_proc', as: 'process_dataset'
  get 'datasets/calc_stats/:id' => 'datasets#calc_stats', as: 'calc_dataset_stats'
  get 'datasets/word_data/:id/:type/:slice' => 'datasets#get_data', as: 'dataset_data',
      constraints: ->(req) { req.format == :json }
  get 'datasets/relate_data/:id/:type' => 'datasets#get_relate_data',
      as: 'dataset_relate_data', constraints: ->(req) { req.format == :json }

  get 'home/pull/:key' => 'home#pull', as: 'new_dataset'
  get 'home/update_synonyms' => 'home#update_synonyms', as: 'update_synonyms'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/source.rb
# frozen_string_literal: true

class Source < ApplicationRecord
  default_scope { where( discarded: false ).order(:citation) }
  belongs_to :dataset, inverse_of: :sources, optional: true
  has_and_belongs_to_many :authors, inverse_of: :sources
  belongs_to :topic, inverse_of: :sources
  has_many :factors, inverse_of: :source, dependent: :destroy
  has_many :words, through: :factors
  has_many :stems, through: :words
  has_many :synonyms, through: :words

  has_and_belongs_to_many :refs,
                          class_name: 'Source',
                          join_table: :references,
                          foreign_key: :source_id,
                          association_foreign_key: :reference_source_id,
                          dependent: :destroy

  @@filter = Stopwords::Snowball::Filter.new('en')

  def self.filter
    @@filter
  end

  def preproc
    self.processed = false
    save
    PreProcSourceJob.perform_later(source: self)
  end

  def add_refs(source_text:)
    self.refs_processed = false
    save
    AddRefsFromBiblioJob.perform_later(source_text: source_text, source: self)
  end

  def unverifieds
    unverifieds = []
    factors.each do |factor|
      unverifieds.concat(factor.unverified.split(/\W+/)) unless factor.unverified.blank?
    end
    unverifieds
  end

  def get_word_counts
    require 'zlib'
    word_counts = nil
    if word_cache.blank?
      word_counts = words.group( :raw ).count
    else
      word_counts = Zlib::Inflate.inflate( Base64.decode64(word_cache) )
      word_counts = JSON.parse( word_counts )
    end
    word_counts
  end

  def get_stem_counts
    require 'zlib'
    stem_cache.blank? ? stems.group(:word).count : 
        JSON.parse( Zlib::Inflate.inflate( Base64.decode64(stem_cache) ) )
  end

  def get_synonym_counts
    synonym_cache.blank? ? synonyms.group(:word).count :
        JSON.parse( Zlib::Inflate.inflate( Base64.decode64(synonym_cache) ) )
  end
end

app/controllers/sources_controller.rb
# frozen_string_literal: true

class SourcesController < ApplicationController
  before_action :set_source

  def show
    @stats = {}
    @stats = JSON.parse(@source.stats_cache) if @source.stats_cache.present?
  end

  def edit; end

  def update
    if @source.update(source_params)
      redirect_to source_path(@source), notice: 'Updated!'
    else
      render :edit
    end
  end

  def add_refs
    # Add any references here
    @source.add_refs(source_text: params[:sources])
    redirect_to source_path(@source)
  end

  def data_proc
    @source.preproc
    redirect_to source_path(@source)
  end

  def get_relate_data
    links = []
    nodes = []
    case params[:type].downcase
    when 'authors'
      links = get_source_refs source: @source
      links.each do |link|
        nodes << { id: link[:target].id,
                    name: link[:target].citation
                 }
        link[:source] = link[:source].id
        link[:target] = link[:target].id
      end

    when 'sources'
    end
    data = { nodes: nodes, links: links }
    respond_to do |format|
      format.json { render json: data }
    end
  end

  def get_source_refs( source: )
    links = [ ]
    source.refs.each do |ref|
      links << { source: source,
                 target: ref,
                 value: ref.year
               }
      if ref.refs.count > 0
        links += get_source_refs( ref )
      end
    end
    links
  end

  def get_data
    counts = {}
    case params[:type].downcase
    when 'stems'
      counts = @source.get_stem_counts
      stat_key = 'top stems'
    when 'words'
      counts = @source.get_word_counts
      stat_key = 'top words'
    when 'synonyms'
      counts = @source.get_synonym_counts
      stat_key = 'top synonyms'
    end


    unless @source.stats_cache.blank?
      stats = JSON.parse(@source.stats_cache) if @source.stats_cache.present?
      max = nil
      min = nil
      sd = stats[stat_key]['standard_deviation']
      case params[:slice].downcase
      when 'all'
      when 'bottom'
        max = stats[stat_key]['mean'] - 2 * sd
      when 'lower half'
        max = stats[stat_key]['mean']
      when 'upper half'
        min = stats[stat_key]['mean']
      when 'within 1sd'
        max = stats[stat_key]['mean'] + sd
        min = stats[stat_key]['mean'] - sd
      when 'within 2sd'
        max = stats[stat_key]['mean'] + 2 * sd
        min = stats[stat_key]['mean'] - 2 * sd
      when 'lower 1sd'
        max = stats[stat_key]['mean']
        min = stats[stat_key]['mean'] - sd
      when 'upper 1sd'
        min = stats[stat_key]['mean']
        max = stats[stat_key]['mean'] + sd
      when 'lower 2sd'
        max = stats[stat_key]['mean']
        min = stats[stat_key]['mean'] - 2 * sd
      when 'upper 2sd'
        min = stats[stat_key]['mean']
        max = stats[stat_key]['mean'] + 2 * sd
      when 'between 1sd and 2sd up'
        min = stats[stat_key]['mean'] + sd
        max = stats[stat_key]['mean'] + 2 * sd
      when 'top'
        min = stats[stat_key]['mean'] - 2 * sd
      end

      counts = counts.delete_if { |_key, value| (min.present? && value < min) || (max.present? && value > max) }

    end

    respond_to do |format|
      format.json { render json: counts.to_a }
    end
  end

  def destroy
    @source.destroy
    redirect_to dataset_path(@source.dataset)
  end

  private

  def set_source
    @source = Source.find(params[:id])
  end

  def source_params
    params.require(:source).permit(:citation,
                                   :author_list, :year, :purpose,
                                   :topic_id, :discard_reason, :title)
  end
end

app/views/sources/_form.html.erb
<%= simple_form_for @source do |f| %>
  <%= f.error_notification %>
  <div class='form-inputs'>
    <%= f.input :citation %>
    <%= f.input :title %>
    <%= f.input :author_list %>
    <%= f.association :authors %>
    <%= f.input :year %>
    <%= f.association :topic %>
    <%= f.input :purpose %>
    <%= f.input :discard_reason %>
  </div>
  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1>Sources Edit</h1>
<%= render 'form' %>
<%= link_to 'Show', source_path( @source ) %> |
<%= link_to 'Back', dataset_path( @source.dataset ) %><br>

app/views/sources/show.html.erb
<h1>Source Show</h1>
<strong>Title:</strong> <%= @source.title %></br>
<strong>Year:</strong> <%= @source.year %></br>
<strong>Purpose:</strong> <%= @source.purpose %></br>
<% unless @source.discard_reason.blank? %>
<strong>Discard Reason:</strong> <%= @source.discard_reason %></br>
<% end %>
<strong>Topic:</strong> <%= @source.topic.name %></br>
<strong>Processed:</strong> <%= @source.processed %></br>
</br>
<h2>Source Authors:</h2>
<ul><% @source.authors.each do |author| %>
  <li><%= author.given_name %> <%= author.family_name %></li>
<% end %></ul>
</br>
<% @stats.each do |key,counts|
  stat_pack = counts.values.extend(DescriptiveStatistics)
end %>
<% unless @stats.values.empty? %>
<table>
    <tr>
      <th>Type</th>
      <% @stats.values[0].keys.each do |key| %>
      <th><%= key %></th>
      <% end %>
    </tr>
    <% @stats.each do |key,stats| %>
    <tr>
      <th><%= key %></th>
      <% stats.keys.each do |stat_key| %>
      <th><%= stats[ stat_key ] %></th>
      <% end %>
    </tr>
    <% end %>
</table>
<% end %>

<i><strong>Citation:</strong> <%= @source.citation %></i>

<% unless @source.unverifieds.empty? %>
  <h2>Spelling problems:</h2>
  <ul><% @source.unverifieds.each do |unver| %>
    <li>
      <%= unver %>
      <ol><% Spellchecker.check( unver, dictionary = 'en' )[ 0 ][:suggestions].each do |sugg| %>
        <li><%= sugg %></li>
      <% end %></ol>
    </li>
  <% end %></ul>
<% end %>
<br><br>

<input type="hidden" id="granularity" value="sources">
<input type="hidden" id="source_id" value="<%=@source.id %>">
<select id="word_count_opt">
  <option>Words</option>
  <option>Stems</option>
  <option>Synonyms</option>
</select><br>
<select id="slice_opt">
  <option>All</option>
  <option>bottom</option>
  <option>lower half</option>
  <option>upper half</option>
  <option>within 1sd</option>
  <option>within 2sd</option>
  <option>lower 1sd</option>
  <option>upper 1sd</option>
  <option>lower 2sd</option>
  <option>between 1sd and 2sd up</option>
  <option>upper 2sd</option>
  <option>top</option>
</select><br>
<select name="words" id="words" size="30">
</select>
<svg id="word_counts" width="500" height="500" font-family="sans-serif"
  font-size="10" text-anchor="middle">
</svg>


<h2>Factors:</h2>
<ul><% @source.factors.each do |factor| %>
  <li>
    <%= factor.text %>
    <ul>
    <% factor.words.each do |word| %>
      <li>
        <%= word.raw %> | <%= word.stem.word %>
      </li>
    <% end %>
    </ul>
    <% unless factor.unverified.blank? %>
    <li>Unverified: <%= factor.unverified %></li>
    <% end %>
  </li>
<% end %></ul>


<h2>Cited Sources:</h2>
<ul><% @source.refs.each do |ref| %>
  <li><%= ref.citation %></li>
<% end %></ul>
<select id="relate_opt">
  <option>Authors</option>
  <option>Sources</option>
</select><br>
<svg id="relationships" width="500" height="500" 
  font-family="sans-serif" font-size="10" text-anchor="middle">
</svg>


<h1>Add Sources</h1>
<%= form_tag add_refs_to_source_path( @source ) do %>
  <%= text_area_tag 'sources', '', size: "100x25" %>
  <%= submit_tag 'Add ''em!' %>
<% end %>

<%= link_to "Edit Source", edit_source_path( @source ) %><br>