config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :datasets, only: %i[show edit update destroy]
  resources :sources, only: %i[show edit update destroy]

  post 'sources/add_refs/:id' => 'sources#add_refs', as: 'add_refs_to_source'
  get 'sources/process/:id' => 'sources#data_proc', as: 'process_source'
  get 'sources/word_data/:id/:type/:slice' => 'sources#get_data', as: 'source_data',
      constraints: ->(req) { req.format == :json }
  get 'sources/relate_data/:id/:type' => 'sources#get_relate_data',
      as: 'source_relate_data', constraints: ->(req) { req.format == :json }

  get 'datasets/process/:id' => 'datasets#data_proc', as: 'process_dataset'
  get 'datasets/calc_stats/:id' => 'datasets#calc_stats', as: 'calc_dataset_stats'
  get 'datasets/word_data/:id/:type/:slice' => 'datasets#get_data', as: 'dataset_data',
      constraints: ->(req) { req.format == :json }
  get 'datasets/relate_data/:id/:type' => 'datasets#get_relate_data',
      as: 'dataset_relate_data', constraints: ->(req) { req.format == :json }

  get 'home/pull/:key' => 'home#pull', as: 'new_dataset'
  get 'home/update_synonyms' => 'home#update_synonyms', as: 'update_synonyms'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/dataset.rb
# frozen_string_literal: true

class Dataset < ApplicationRecord
  belongs_to :user, inverse_of: :datasets
  has_many :sources, inverse_of: :dataset, dependent: :destroy
  has_many :factors, through: :sources
  has_many :words, through: :factors
  has_many :stems, through: :words
  has_many :synonyms, through: :words

  def percent_processed
    (100 * sources.where(processed: true).count.to_f / sources.count).to_i unless sources.count == 0
  end

  def get_word_counts
    counts = {}
    sources.find_each do |source|
      counts.merge!(source.get_word_counts) { |_key, v1, v2| v1 + v2 }
    end
    counts
  end

  def get_stem_counts
    counts = {}
    sources.each do |source|
      counts.merge!(source.get_stem_counts) { |_key, v1, v2| v1 + v2 }
    end
    counts
  end

  def get_synonym_counts
    counts = {}
    sources.each do |source|
      counts.merge!(source.get_synonym_counts) { |_key, v1, v2| v1 + v2 }
    end
    counts
  end
end

app/controllers/datasets_controller.rb
# frozen_string_literal: true

class DatasetsController < ApplicationController
  before_action :set_dataset

  def show
    # Build out any history support.
    @stats = {}
    @stats = JSON.parse(@dataset.stats_cache) if @dataset.stats_cache.present?
  end

  def edit; end

  def update
    if @dataset.update(dataset_params)
      redirect_to dataset_path(@dataset), notice: 'Updated!'
    else
      render :edit
    end
  end

  def destroy
    @dataset.destroy
    redirect_to :root
  end

  def data_proc
    @dataset.sources.each(&:preproc)
    redirect_to dataset_path(@dataset)
  end

  def calc_stats
    DatasetStatsJob.perform_later(dataset: @dataset)
    redirect_to dataset_path(@dataset)
  end

  def get_data
    counts = {}
    case params[:type].downcase
    when 'stems'
      counts = @dataset.get_stem_counts
      stat_key = 'top stems'
    when 'words'
      counts = @dataset.get_word_counts
      stat_key = 'top words'
    when 'synonyms'
      counts = @dataset.get_synonym_counts
      stat_key = 'top synonyms'
    end

    unless @dataset.stats_cache.blank?
      stats = JSON.parse(@dataset.stats_cache) if @dataset.stats_cache.present?
      max = nil
      min = nil
      sd = stats[stat_key]['standard_deviation']
      case params[:slice].downcase
      when 'all'
      when 'bottom'
        max = stats[stat_key]['mean'] - 2 * sd
      when 'lower half'
        max = stats[stat_key]['mean']
      when 'upper half'
        min = stats[stat_key]['mean']
      when 'within 1sd'
        max = stats[stat_key]['mean'] + sd
        min = stats[stat_key]['mean'] - sd
      when 'within 2sd'
        max = stats[stat_key]['mean'] + 2 * sd
        min = stats[stat_key]['mean'] - 2 * sd
      when 'lower 1sd'
        max = stats[stat_key]['mean']
        min = stats[stat_key]['mean'] - sd
      when 'upper 1sd'
        min = stats[stat_key]['mean']
        max = stats[stat_key]['mean'] + sd
      when 'lower 2sd'
        max = stats[stat_key]['mean']
        min = stats[stat_key]['mean'] - 2 * sd
      when 'upper 2sd'
        min = stats[stat_key]['mean']
        max = stats[stat_key]['mean'] + 2 * sd
      when 'between 1sd and 3sd up'
        min = stats[stat_key]['mean'] + sd
        max = stats[stat_key]['mean'] + 3 * sd
      when 'between 1sd and 2sd up'
        min = stats[stat_key]['mean'] + sd
        max = stats[stat_key]['mean'] + 2 * sd
      when 'top'
        min = stats[stat_key]['mean'] + 2 * sd
      when '1sd above'
        min = stats[stat_key]['mean'] + sd
      end

      counts = counts.delete_if { |_key, value| (min.present? && value < min) || (max.present? && value > max) }

    end

    respond_to do |format|
      format.json { render json: counts.sort }
    end
  end

  private

  def set_dataset
    @dataset = Dataset.find(params[:id])
  end

  def dataset_params
    params.require(:dataset).permit(:name,
                                    source: %i[citation year title
                                               discard_reason topic_id
                                               purpose])
  end
end

app/helpers/datasets_helper.rb
# frozen_string_literal: true

module DatasetsHelper
end

app/views/datasets/_form.html.erb
<%= simple_form_for @dataset do |f| %>
  <%= f.error_notification %>
  <div class='form-inputs'>
    <%= f.input :name %>
  </div>
  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/datasets/edit.html.erb
<h1>Datasets Edit</h1>
<%= render 'form' %>
<%= link_to 'Show', dataset_path( @dataset ) %> |
<%= link_to 'Datasets', root_path %>

app/views/datasets/show.html.erb
<h1>Show Dataset</h1>
<strong>Name:</strong> <%= @dataset.name %></br>
<p>This dataset contains <%= @dataset.factors.count %> factors.
  So far, <%= @dataset.sources.count %>
  sources (below) contribute to this data.
</p>
<% unless @stats.values.empty? %>
  <table>
      <tr>
        <th>Type</th>
        <% @stats.values[0].keys.each do |key| %>
        <th><%= key %></th>
        <% end %>
      </tr>
      <% @stats.each do |key,stats| %>
      <tr>
        <th><%= key %></th>
        <% stats.keys.each do |stat_key| %>
        <th><%= stats[ stat_key ] %></th>
        <% end %>
      </tr>
      <% end %>
  </table>
  <%= link_to 'Re-Calculate Stats', calc_dataset_stats_path( @dataset ) %></br>
<% else %>
  No stats calculated yet: <%= link_to 'Calculate them now?', calc_dataset_stats_path( @dataset ) %></br>
<% end %>
<br><br>
<br>
<%= @dataset.percent_processed %>% Sources Processed&nbsp;
    <%= link_to '[re-process dataset sources]', process_dataset_path( @dataset ) %></br>
<br>

<hr>
<input type="hidden" id="granularity" value="datasets">
<input type="hidden" id="source_id" value="<%=@dataset.id %>">
<select id="word_count_opt">
  <option>Words</option>
  <option>Stems</option>
  <option>Synonyms</option>
</select><br>
<select id="slice_opt">
  <option>All</option>
  <% unless @dataset.stats_cache.blank? %>
  <option>bottom</option>
  <option>lower half</option>
  <option>upper half</option>
  <option>within 1sd</option>
  <option>within 2sd</option>
  <option>lower 1sd</option>
  <option>upper 1sd</option>
  <option>lower 2sd</option>
  <option>between 1sd and 2sd up</option>
  <option>between 1sd and 3sd up</option>
  <option>upper 2sd</option>
  <option>1sd above</option>
  <option>top</option>
  <% end %>
</select><br>
<br><div id="words_found"></div><br>

<select name="words" id="words" size="30">
</select>
<svg id="word_counts" width="500" height="500" font-family="sans-serif"
  font-size="10" text-anchor="middle">
</svg>
<hr>
<ul><% @dataset.sources.each do |source| %>
  <li>
     <%= link_to source.citation, source_path( source ) %> 
      <ul>
        <li><%= source.processed ? 'Processed' : 'Unprocessed' %></li>
        <li><%= link_to '[process]', process_source_path( source ) %></li>
        <li>References: <%= source.refs_processed ? 'Fully Processed' : 'Incomplete' %></li>
        <li>Sources attached: <%= source.refs.count %></li>
        <li><%= source.unverifieds.blank? ? 'OK' : raw( '<strong>spelling problems</strong>') %></li>
      </ul>
  </li>
<% end %></ul>

<%= link_to "Edit Dataset", edit_dataset_path( @dataset ) %><br>