config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :datasets, only: %i[show edit update destroy]
  resources :sources, only: %i[show edit update destroy]

  post 'sources/add_refs/:id' => 'sources#add_refs', as: 'add_refs_to_source'
  get 'sources/process/:id' => 'sources#data_proc', as: 'process_source'
  get 'sources/word_data/:id/:type/:slice' => 'sources#get_data', as: 'source_data',
      constraints: ->(req) { req.format == :json }
  get 'sources/relate_data/:id/:type' => 'sources#get_relate_data',
      as: 'source_relate_data', constraints: ->(req) { req.format == :json }

  get 'datasets/process/:id' => 'datasets#data_proc', as: 'process_dataset'
  get 'datasets/calc_stats/:id' => 'datasets#calc_stats', as: 'calc_dataset_stats'
  get 'datasets/word_data/:id/:type/:slice' => 'datasets#get_data', as: 'dataset_data',
      constraints: ->(req) { req.format == :json }
  get 'datasets/relate_data/:id/:type' => 'datasets#get_relate_data',
      as: 'dataset_relate_data', constraints: ->(req) { req.format == :json }

  get 'home/pull/:key' => 'home#pull', as: 'new_dataset'
  get 'home/update_synonyms' => 'home#update_synonyms', as: 'update_synonyms'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @datasets = Dataset.all

    current_user.refresh_token_if_expired
    session = GoogleDrive::Session.from_access_token(current_user.token)

    @sheets = session.spreadsheets(q: 'trashed != true',
                                   corpus: 'user',
                                   orderBy: 'viewedByMeTime desc',
                                   pageSize: 10)
  end

  def pull
    key = params[:key]
    LoadDataJob.perform_later(task_user: current_user, key: key)
    redirect_to :root
  end

  # This is not thread safe!!!
  # Would be good to add a mutex
  def update_synonyms
    UpdateThesaurusJob.perform_later
    redirect_to :root
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/index.html.erb
<H1>Existing Datasets</H1>
<ul>
  <% @datasets.each do |ds| %>
  <li><%= link_to ds.name,  dataset_path( id: ds.id ) %>
        [ <%= ds.load_pct %>% loaded | <%= ds.percent_processed %>% processed &mdash;
          <%=link_to 'process now', process_dataset_path( ds ) %>&nbsp;|&nbsp;
          <%= link_to 'Destroy', ds, method: :delete, data: { confirm: "Are you sure?" } %>]</li>
  <% end %>
</ul>
<%= link_to "Consult Thesaurus", update_synonyms_path %></br>
<h1>Your Spreadsheets</h1>
<ul>
  <% @sheets.each do |ss| %>
  <li><%= link_to ss.title, ss.human_url, target: '_blank' %> |
    <%= link_to 'process', new_dataset_path( key: ss.key ) %></li>
  <% end %>
</ul>